#!/bin/sh
# Generate src/themes_tab.h from scripts/themes.map. Run manually when
# the map changes; the header is checked in.
#
# Layout: ltheme_names[] (sorted, exact-match), ltheme_styles[theme]
# [key] as SGR string literals (NULL = fall back to the built-in
# default style for that key). Key order is the fixed LTHEME_K_* enum
# emitted here and consumed by colors.c.
#
# Invariants (exit 1): known keys, SGR charset [0-9;], no duplicate
# (theme, key), theme name charset [a-z0-9-].
set -eu
cd "$(dirname "$0")/.." || exit 1

map=scripts/themes.map
out=src/themes_tab.h

LC_ALL=C awk '
function fail(msg) { printf "gen-themes-tab: %s\n", msg > "/dev/stderr"; exit 1 }
BEGIN {
    nk = split("fi di ln pi bd cd so ex or " \
               "ur uw ux ue gr gw gx tr tw tx su sf " \
               "lc lm uu un gu gn nb nk nm ng nt df ds " \
               "da in bl xx ga gm gd gv gt gi gc " \
               "im vi mu lo cr do co tm cm bu sc", keys, " ")
    for (i = 1; i <= nk; i++) kidx[keys[i]] = i - 1
    nthemes = 0
}
/^[ \t]*(#|$)/ { next }
{
    t = $1; k = $2; s = $3
    if (t !~ /^[a-z0-9-]+$/) fail("bad theme name: " $0)
    if (t == "default") fail("default is reserved: " $0)
    if (!(k in kidx)) fail("unknown key: " $0)
    if (s !~ /^[0-9;]+$/) fail("bad SGR: " $0)
    if (!(t in tid)) {
        tid[t] = nthemes
        tname[nthemes] = t
        nthemes++
    }
    if ((t, k) in seen) fail("duplicate: " t " " k)
    seen[t, k] = 1
    style[tid[t], kidx[k]] = s
}
END {
    printf "/* GENERATED by scripts/gen-themes-tab.sh from scripts/themes.map.\n"
    printf "   Do not edit; edit the map and regenerate. */\n\n"
    printf "enum {\n"
    for (i = 1; i <= nk; i++)
        printf "    LTHEME_K_%s = %d,\n", toupper(keys[i]), i - 1
    printf "    LTHEME_N_KEYS = %d\n};\n\n", nk
    printf "#define LTHEME_N_THEMES %d\n\n", nthemes
    printf "static const char *const ltheme_names[LTHEME_N_THEMES] = {\n"
    for (i = 0; i < nthemes; i++)
        printf "    \"%s\",\n", tname[i]
    printf "};\n\n"
    printf "static const char *const ltheme_styles[LTHEME_N_THEMES][LTHEME_N_KEYS] = {\n"
    for (i = 0; i < nthemes; i++) {
        printf "    {\n"
        for (j = 0; j < nk; j++) {
            if ((i, j) in style)
                printf "        \"%s\",\n", style[i, j]
            else
                printf "        NULL,\n"
        }
        printf "    },\n"
    }
    printf "};\n"
}
' "$map" > "$out.tmp"
mv "$out.tmp" "$out"
echo "gen-themes-tab: wrote $out"
