#!/bin/sh
# Generate src/colorclass_tab.h from scripts/colorclass.map. Run
# manually when the map changes; the header is checked in.
#
# Layout mirrors icons_tab.h: key pools + entry arrays bucketed by
# case-folded final byte with 257-entry offset indexes. Extensions are
# stored lowercased (matched against the lowercased last-dot ext);
# filenames case-sensitive. Classes are indexes into the fixed
# LISZT_CC_* order in colors.h.
#
# Invariants (exit 1): known class names, no duplicate keys per table,
# offsets fit uint16.
set -eu
cd "$(dirname "$0")/.." || exit 1

map=scripts/colorclass.map
out=src/colorclass_tab.h

LC_ALL=C awk '
function fail(msg) { printf "gen-colorclass-tab: %s\n", msg > "/dev/stderr"; exit 1 }
function fold(s,   r, i, c) {
    r = ""
    for (i = 1; i <= length(s); i++) {
        c = substr(s, i, 1)
        if (c >= "A" && c <= "Z")
            c = sprintf("%c", index("ABCDEFGHIJKLMNOPQRSTUVWXYZ", c) + 96)
        r = r c
    }
    return r
}
BEGIN {
    for (i = 0; i < 256; i++) ord[sprintf("%c", i)] = i
    nc = split("Image Video Music Lossless Crypto Document Compressed " \
               "Temp Compiled Build Source", cls, " ")
    for (i = 1; i <= nc; i++) clsidx[cls[i]] = i - 1
}
/^[ \t]*(#|$)/ { next }
{
    tag = $1; key = $2; cn = $3
    if (tag !~ /^[nx]$/) fail("bad tag: " $0)
    if (!(cn in clsidx)) fail("unknown class: " $0)
    if (tag == "x") key = fold(key)
    if ((tag, key) in seen) fail("duplicate key: " $0)
    seen[tag, key] = 1
    n[tag]++
    K[tag, n[tag]] = key
    C[tag, n[tag]] = clsidx[cn]
}
END {
    printf "/* GENERATED by scripts/gen-colorclass-tab.sh from scripts/colorclass.map.\n"
    printf "   Do not edit; edit the map and regenerate. */\n\n"
    printf "struct lcc_ent { uint16_t key_off; uint8_t key_len; uint8_t class; };\n\n"

    split("n x", tags, " ")
    tname["n"] = "name"; tname["x"] = "ext"
    for (ti = 1; ti <= 2; ti++) {
        t = tags[ti]
        cnt = n[t] + 0
        m = 0
        for (b = 0; b < 256; b++) {
            bstart[b] = m
            for (i = 1; i <= cnt; i++) {
                k = K[t, i]
                if (ord[substr(fold(k), length(k), 1)] == b)
                    order[t, m++] = i
            }
        }
        bstart[256] = m

        printf "static const char lcc_%s_pool[] =\n", tname[t]
        off = 0
        for (i = 0; i < m; i++) {
            k = K[t, order[t, i]]
            if (off + length(k) > 65535) fail("pool exceeds uint16")
            pooloff[t, i] = off
            gsub(/\\/, "\\\\", k)
            gsub(/"/, "\\\"", k)
            printf "    \"%s\"\n", k
            off += length(K[t, order[t, i]])
        }
        if (m == 0) printf "    \"\"\n"
        printf ";\n\n"

        printf "static const struct lcc_ent lcc_%s_tab[%d] = {\n", tname[t], m ? m : 1
        for (i = 0; i < m; i++) {
            k = K[t, order[t, i]]
            if (length(k) > 255) fail("key too long: " k)
            printf "    { %d, %d, %d },\n", pooloff[t, i], length(k), C[t, order[t, i]]
        }
        if (m == 0) printf "    { 0, 0, 0 },\n"
        printf "};\n\n"

        printf "static const uint16_t lcc_%s_bucket[257] = {\n    ", tname[t]
        for (b = 0; b <= 256; b++) {
            printf "%d,", bstart[b]
            if (b % 16 == 15) printf "\n    "
        }
        printf "\n};\n\n"
        delete bstart
    }
}
' "$map" > "$out.tmp"
mv "$out.tmp" "$out"
echo "gen-colorclass-tab: wrote $out"
