#!/bin/sh
# Generate src/icons_tab.h from scripts/icons.map. Run manually when
# the map changes; the header is checked in and never rebuilt by make.
#
# Layout (locked, sprint 12): deduped glyph pool (uint8 index), key
# pools + entry arrays for the three key tables (filename, dirname,
# extension) grouped by case-folded final byte with 257-entry bucket
# offset indexes precomputed; extension entries longest-first within a
# bucket; filetype defaults keyed by the LS_COLORS label order used by
# colors.c's indicator_name[].
#
# Invariants enforced (exit 1): codepoint parses, single codepoint per
# glyph, codepoint in the width-1-assumed set (printable ASCII, the
# BMP symbol blocks 2000-2BFF, BMP PUA E000-F8FF, SPUA-A F0000-FFFFD),
# no duplicate keys per table, offsets fit uint16. The authoritative
# width-1 check (liszt_uc_width) runs in the
# unit self-test, which compiles against src/uniwidth.c.
set -eu
cd "$(dirname "$0")/.." || exit 1

map=scripts/icons.map
out=src/icons_tab.h

LC_ALL=C awk '
function fail(msg) { printf "gen-icons-tab: %s\n", msg > "/dev/stderr"; bad = 1; exit 1 }
function fold(s,   r, i, c) {
    r = ""
    for (i = 1; i <= length(s); i++) {
        c = substr(s, i, 1)
        if (c >= "A" && c <= "Z") c = sprintf("%c", index("ABCDEFGHIJKLMNOPQRSTUVWXYZ", c) + 96)
        r = r c
    }
    return r
}
function utf8(cp,   s) {
    if (cp < 0x80) return sprintf("%c", cp)
    if (cp < 0x800)
        return sprintf("%c%c", 0xC0 + int(cp / 64), 0x80 + cp % 64)
    if (cp < 0x10000)
        return sprintf("%c%c%c", 0xE0 + int(cp / 4096),
                       0x80 + int(cp / 64) % 64, 0x80 + cp % 64)
    return sprintf("%c%c%c%c", 0xF0 + int(cp / 262144),
                   0x80 + int(cp / 4096) % 64,
                   0x80 + int(cp / 64) % 64, 0x80 + cp % 64)
}
function cbytes(s,   r, i) {   # C string escape of raw bytes
    r = ""
    for (i = 1; i <= length(s); i++)
        r = r sprintf("\\%03o", ord[substr(s, i, 1)])
    return r
}
function hexval(s,   i, c, v) {
    v = 0
    for (i = 1; i <= length(s); i++) {
        c = index("0123456789abcdef", tolower(substr(s, i, 1)))
        if (c == 0) fail("bad hex: " s)
        v = v * 16 + c - 1
    }
    return v
}
function glyph_index(cp,   b) {
    if (cp in gidx) return gidx[cp]
    if (nglyph >= 65535) fail("glyph index exceeds uint16")
    gidx[cp] = nglyph
    gcp[nglyph] = cp
    nglyph++
    return gidx[cp]
}
BEGIN {
    for (i = 0; i < 256; i++) ord[sprintf("%c", i)] = i
    nglyph = 0
    # LS_COLORS label order must match colors.c indicator_name[].
    nlab = split("lc rc ec rs no fi di ln pi so bd cd mi or ex do su sg st ow tw ca mh cl", lab, " ")
    for (i = 1; i <= nlab; i++) labidx[lab[i]] = i - 1
}
/^[ \t]*(#|$)/ { next }
{
    tag = $1; key = $2; cps = $3
    if (tag !~ /^[ndxt]$/) fail("bad tag: " $0)
    if (cps !~ /^U\+[0-9A-Fa-f]+$/) fail("bad codepoint: " $0)
    cp = hexval(substr(cps, 3))
    ok = (cp >= 0x20 && cp < 0x7F) || (cp >= 0x2000 && cp <= 0x2BFF) || \
         (cp >= 0xE000 && cp <= 0xF8FF) || (cp >= 0xF0000 && cp <= 0xFFFFD)
    if (!ok) fail("codepoint outside width-1-assumed set: " $0)
    if (tag == "t") {
        if (!(key in labidx)) fail("unknown filetype label: " $0)
        tglyph[labidx[key]] = glyph_index(cp)
        next
    }
    if (tag == "x") {
        if (substr(key, 1, 1) != ".") fail("suffix without dot: " $0)
        key = fold(key)
    }
    if ((tag, key) in seen) fail("duplicate key: " $0)
    seen[tag, key] = 1
    n[tag]++
    K[tag, n[tag]] = key
    G[tag, n[tag]] = glyph_index(cp)
}
END {
    if (bad) exit 1
    printf "/* GENERATED by scripts/gen-icons-tab.sh from scripts/icons.map.\n"
    printf "   Do not edit; edit the map and regenerate. */\n\n"
    printf "struct licon_glyph { unsigned char len; char bytes[4]; };\n"
    printf "struct licon_ent { uint16_t key_off; uint8_t key_len; uint16_t glyph; };\n\n"

    printf "static const struct licon_glyph licon_glyphs[%d] = {\n", nglyph
    for (g = 0; g < nglyph; g++) {
        b = utf8(gcp[g])
        printf "    { %d, \"%s\" },\n", length(b), cbytes(b)
    }
    printf "};\n\n"

    split("n d x", tags, " ")
    tname["n"] = "name"; tname["d"] = "dir"; tname["x"] = "ext"
    for (ti = 1; ti <= 3; ti++) {
        t = tags[ti]
        # bucket by folded final byte; ext longest-first within bucket
        cnt = n[t] + 0
        for (i = 1; i <= cnt; i++) {
            k = K[t, i]
            fb = ord[substr(fold(k), length(k), 1)]
            border[i] = fb
        }
        # stable selection sort into bucket order (longest-first for x)
        m = 0
        for (b = 0; b < 256; b++) {
            for (pass = 0; pass < 1; pass++) {
                # collect indexes in bucket b
                nb = 0
                for (i = 1; i <= cnt; i++)
                    if (border[i] == b) blist[++nb] = i
                if (t == "x" && nb > 1) {
                    for (i = 1; i < nb; i++)
                        for (j = i + 1; j <= nb; j++)
                            if (length(K[t, blist[j]]) > length(K[t, blist[i]])) {
                                tmp = blist[i]; blist[i] = blist[j]; blist[j] = tmp
                            }
                }
                bstart[b] = m
                for (i = 1; i <= nb; i++) {
                    order[t, m] = blist[i]
                    m++
                }
            }
        }
        bstart[256] = m

        pool = ""
        printf "static const char licon_%s_pool[] =\n", tname[t]
        off = 0
        for (i = 0; i < m; i++) {
            k = K[t, order[t, i]]
            if (t == "x") k = fold(k)
            if (off + length(k) > 65535) fail("key pool exceeds uint16")
            pooloff[t, i] = off
            printf "    \"%s\"\n", cbytes(k)
            off += length(k)
        }
        if (m == 0) printf "    \"\"\n"
        printf ";\n\n"

        printf "static const struct licon_ent licon_%s_tab[%d] = {\n", tname[t], m ? m : 1
        for (i = 0; i < m; i++) {
            k = K[t, order[t, i]]
            if (length(k) > 255) fail("key too long: " k)
            printf "    { %d, %d, %d },\n", pooloff[t, i], length(k), G[t, order[t, i]]
        }
        if (m == 0) printf "    { 0, 0, 0 },\n"
        printf "};\n\n"

        printf "static const uint16_t licon_%s_bucket[257] = {\n    ", tname[t]
        for (b = 0; b <= 256; b++) {
            printf "%d,", bstart[b]
            if (b % 16 == 15) printf "\n    "
        }
        printf "\n};\n\n"
        delete border; delete blist; delete bstart
    }

    printf "static const uint16_t licon_class_glyph[24] = {\n    "
    for (i = 0; i < 24; i++) {
        printf "%s,", (i in tglyph) ? tglyph[i] : 65535
        if (i % 12 == 11) printf "\n    "
    }
    printf "\n};\n"
}
' "$map" > "$out.tmp"
mv "$out.tmp" "$out"
echo "gen-icons-tab: wrote $out"
